### ISSUE TITLE
Move documentation to a system that allows source control

### ISSUE THREAD

**Issue by chriska85** [ntnuiotenergy/OpenEMPIRE#8]
The current documentation practice, writing the documentation in a MS word file and converting to a pdf, does not allow for proper source control and may prohibit (or at least complicate) community contributions.

The documentation should be moved to a system that better allows source control, such as sphinx or readthedocs.

**Comment by martinhjel** [comment]
Solved by #33. 

See: https://openempire.readthedocs.io/en/latest/
